### PR TITLE
Fixed rendering of functional react components

### PR DESCRIPTION
**Pull request by SergeyShvager**
I have a problem with rendering functional react component because of not safe code in the `elementPrototype.createdCallback` and I had errors like:
```
reactive-elements.js:29 Uncaught TypeError: Cannot read property 'props' of null
    at HTMLElement.elementPrototype.createdCallback (reactive-elements.js:29)
    at webpackJsonp../node_modules/reactive-elements/src/reactive-elements.js.exports.registerReact (
```

`ReactDOM.render` returns null if you pass functional component. I've wrapped not safe code with check for not null.

### CODE REVIEW

**Comment by jackfranklin** [comment]
Plus one for this; we're seeing a lot of these warnings. Is there any hope of this being merged (if this proj is being maintained anymore?).

We're using this a lot and I'd be willing to help maintain, triage issues, and so on if you need help.

**Comment by PixelsCommander** [comment]
@SergeyShvager thanks for this PR it looks reasonable and I believe should be merged ASAP after being reviewed!

@jackfranklin I just got back from holidays and am extremely overloaded until next week. Could you review this one, check if it works and meets your expectations and give a feedback here? I will proceed with merge and NPM update immediately.

**Comment by jackfranklin** [comment]
👍  @SergeyShvager the code looks good but I wonder if it's worth adding in a test case to go with the new functionality? Just checking that it can render a functional component just fine without any errors?

**Comment by SergeyShvager** [comment]
@jackfranklin Agree

**Comment by jackfranklin** [comment]
Are you happy to write them? Else I'm happy to help :)

**Comment by SergeyShvager** [comment]
Sure, I'll add tests

**Comment by SergeyShvager** [comment]
@jackfranklin but probably I need help here. Not sure how to cover rendering of custom elements.

**Comment by jackfranklin** [comment]
Ah I'm sorry, I thought there were already some custom-elements tests. If there aren't then let's merge this for now and look into adding tests another time. @PixelsCommander I think this is good to merge :)

**Comment by PixelsCommander** [comment]
Thanks guys, new version is on NPM. 
Friday evening - best time for a release =) Have a good weekend!

**Comment by SergeyShvager** [comment]
thanks, you too 😄

**Comment by jackfranklin** [comment]
@PixelsCommander thanks!

**Pull request merged**
