### PR TITLE
update react to version 16 and document register element to version 1

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Resolves
```
Uncaught Error: Unable to find node on an unmounted component.
```
when using ReactiveElements with React 16.
See https://github.com/Pomax/react-onclickoutside/issues/231#issuecomment-333174275.

---

Unit tests are passing, I `npm linked` the updated version locally and it passes smoke tests on existing elements.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
:bell: @PixelsCommander @jackfranklin

**Comment by jackfranklin** [comment]
Interesting - I haven't seen this error on React 16.

I worry if we bump to 16 though that will mess with people who are still on React 15 and cannot yet upgrade.

Maybe it makes more sense to turn React into a peer dependency here and ensure it's 15 or 16? What do you think @ChristianMurphy ?

And sorry for the delay in looking at this!

**Comment by jackfranklin** [comment]
@ChristianMurphy are you happy to update the PR? :)

**Comment by ChristianMurphy** [comment]
@jackfranklin updated :ballot_box_with_check:

**Comment by jackfranklin** [comment]
Looks good! Thanks

**Pull request merged**
