### PR TITLE
Support newlines in attribute values

### PR DESCRIPTION
**Pull request by kulor**
Simple change but here's the use case that this fixes:

```
<my-element foo="{[
{"name": "foo"}
...
}]"></my-element>
```

### CODE REVIEW

**Comment by PixelsCommander** [comment]
Hi

Thanks for PR, will check asap

**Comment by kulor** [comment]
I did try running tests `gulp test` but hit this exception before my change:
"Error: No custom element support or polyfill found! at /Users/james/Documents/ReactiveElements/src/reactive-elements.js:7".

**Comment by PixelsCommander** [comment]
There was a refactoring and migration to browserify which may break them

**Comment by kulor** [comment]
hey @PixelsCommander, any chance you could take a look at this today, it's a small change :)

**Comment by PixelsCommander** [comment]
Merged, published to NPM

**Pull request merged**
