### PR TITLE
major refactoring

### PR DESCRIPTION
**Pull request by kof**
- use browserify for modules
- don’t merge components instance with custom element, as ES6 class
methods are not enumerable
- pass `children` and `container` to the component. Now component is
responsible for exposing public methods on container or using dom
events.
- move utils into separate module

### CODE REVIEW

**Comment by kof** [comment]
Any thoughts? @PixelsCommander

**Comment by kof** [comment]
Lets start a discussion, what do you dislike?

**Comment by kof** [comment]
ping

**Comment by PixelsCommander** [comment]
Will be back from holidays on weekend. Sorry for delay

**Comment by kof** [comment]
ok, conflicts resolved

**Pull request merged**
